# Generated by Django 2.1.2 on 2018-12-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(),
        ),
    ]
